# Use the Node.js base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy the necessary files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --production

# Copy the source code
COPY . .

# Build the application
RUN yarn build

# Define the command to run the application
CMD ["node", "dist/server.js"]
